FROM node:boron

RUN mkdir -p /Users/skide/Documents/School AP - ICT/2EA2/DevOps/lab4_Docker/web
WORKDIR /Users/skide/Documents/School AP - ICT/2EA2/DevOps/lab4_Docker/web
RUN npm install
EXPOSE 3000
CMD [ "npm", "start" ]