Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "mgr" do |mgr|
    mgr.vm.hostname = "mgr.site"
    mgr.vm.network :private_network, ip: "192.168.16.10"
    mgr.vm.provision  "shell", path: "bootstrap.sh"

  end
  config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod.site"
    prod.vm.network :private_network, ip: "192.168.16.12"
    prod.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
    prod.vm.network :forwarded_port, guest: 22, host: 6666, auto_correct: true
    prod.vm.provision  "shell", path: "bootstrap.sh"
  end
end